version: '3'
services:
  postgres:
    container_name: ningyotsukai-postgres-1
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
    ports:
      - "5432:5432"
  redis:
    container_name: ningyotsukai-redis-1
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass qwe098poi123
  training:
    container_name: ningyotsukai-training-1
    image: "chazari/ningyotsukai:latest"
    ports:
      - "8081:8081"
    depends_on:
      - redis
    command: [ "/app/main", "training" ]
  bot:
    container_name: ningyotsukai-bot-1
    image: "chazari/ningyotsukai:latest"
    restart: on-failure
    depends_on:
      - redis
      - postgres
    command: ["/app/main", "discord_bot"]