log:
  dev: false
  level: "error"

bot:
  token: "token"
  support:
    id: 0
    href: "https://t.me/user"

redis:
  host: "redis"
  port: "6379"
  password: "qwe908poi123"

db:
  host: "0.0.0.0"
  port: "5432"
  user: "postgres"
  pass: "postgrespw"
  name: "postgres"

schedule:
  groups:
    - id: 114808
      name: "ИСП-Б-231-2021"
    - id: 10888
      name: "ИСП-Б-230-2020"

  teachers:
    - name: "Шевелева Оксана Владимировна"